HaltechDashValue dashValues[] = {
    // Long Name,                    Short Name,   Enum,                      CAN ID, Start B, End B, Incoming Unit,  Scale,  Offset,  Rate, Signed, Last, Scaled, Bit
    {"RPM",                          "RPM",        HT_RPM,                    0x360,  0,       1,     UNIT_RPM,       1.0f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Manifold Pressure",            "MAP",        HT_MANIFOLD_PRESSURE,      0x360,  2,       3,     UNIT_KPA_ABS,   0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Throttle Position",            "TPS",        HT_THROTTLE_POSITION,      0x360,  4,       5,     UNIT_PERCENT,   0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Coolant Pressure",             "CoolPres",   HT_COOLANT_PRESSURE,       0x360,  6,       7,     UNIT_KPA,       0.1f,   -101.3f, 50,   false,  0,    0.0f,   0},
    {"Fuel Pressure",                "FuelPres",   HT_FUEL_PRESSURE,          0x361,  0,       1,     UNIT_KPA,       0.1f,   -101.3f, 50,   false,  0,    0.0f,   0},
    {"Oil Pressure",                 "OilPres",    HT_OIL_PRESSURE,           0x361,  2,       3,     UNIT_KPA,       0.1f,   -101.3f, 50,   false,  0,    0.0f,   0},
    {"Engine Demand",                "EngDemand",  HT_ENGINE_DEMAND,          0x361,  4,       5,     UNIT_PERCENT,   0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Wastegate Pressure",           "WastePres",  HT_WASTEGATE_PRESSURE,     0x361,  6,       7,     UNIT_KPA,       0.1f,   -101.3f, 50,   false,  0,    0.0f,   0},
    {"Injection Stage 1 DC",         "InjS1Duty",  HT_INJ_STATE_1_DUTY,       0x362,  0,       1,     UNIT_PERCENT,   0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Injection Stage 2 DC",         "InjS2Duty",  HT_INJ_STATE_2_DUTY,       0x362,  2,       3,     UNIT_PERCENT,   0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Ignition Angle",               "IgnAngle",   HT_IGNITION_ANGLE,         0x362,  4,       5,     UNIT_DEGREES,   0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"Wheel Slip",                   "WhlSlip",    HT_WHEEL_SLIP,             0x363,  0,       1,     UNIT_KPH,       0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Wheel Diff",                   "WhlDiff",    HT_WHEEL_DIFF,             0x363,  2,       3,     UNIT_KPH,       0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Launch Cont End RPM",          "LCEndRPM",   HT_LAUNCH_CONTROL_END_RPM, 0x363,  6,       7,     UNIT_RPM,       1.0f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Inj Stage 1 Avg Time",         "Inj1AvgTim", HT_INJ1_AVG_TIME,          0x364,  0,       1,     UNIT_MS,        0.001f, 0.0f,    50,   false,  0,    0.0f,   0},
    {"Inj Stage 2 Avg Time",         "Inj2AvgTim", HT_INJ2_AVG_TIME,          0x364,  2,       3,     UNIT_MS,        0.001f, 0.0f,    50,   false,  0,    0.0f,   0},
    {"Inj Stage 3 Avg Time",         "Inj3AvgTim", HT_INJ3_AVG_TIME,          0x364,  4,       5,     UNIT_MS,        0.001f, 0.0f,    50,   false,  0,    0.0f,   0},
    {"Inj Stage 4 Avg Time",         "Inj4AvgTim", HT_INJ4_AVG_TIME,          0x364,  6,       7,     UNIT_MS,        0.001f, 0.0f,    50,   false,  0,    0.0f,   0},
    {"Wideband Sensor 1",            "WB1",        HT_WIDEBAND_SENSOR_1,      0x368,  0,       1,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 2",            "WB2",        HT_WIDEBAND_SENSOR_2,      0x368,  2,       3,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 3",            "WB3",        HT_WIDEBAND_SENSOR_3,      0x368,  4,       5,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 4",            "WB4",        HT_WIDEBAND_SENSOR_4,      0x368,  6,       7,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Trigger Error Count",          "TrigErrCnt", HT_TRIGGER_ERROR_COUNT,    0x369,  0,       1,     UNIT_RAW,       1.0f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Trigger Counter",              "TrigCnt",    HT_TRIGGER_COUNTER,        0x369,  2,       3,     UNIT_RAW,       1.0f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Trigger Sync Level",           "TrigSyncLv", HT_TRIGGER_SYNC_LEVEL,     0x369,  6,       7,     UNIT_RAW,       1.0f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Knock Level 1",                "KnockLvl1",  HT_KNOCK_LEVEL_1,          0x36A,  0,       1,     UNIT_DB,        0.01f,  0.0f,    20,   false,  0,    0.0f,   0},
    {"Knock Level 2",                "KnockLvl2",  HT_KNOCK_LEVEL_2,          0x36A,  2,       3,     UNIT_DB,        0.01f,  0.0f,    20,   false,  0,    0.0f,   0},
    {"Brake Pressure Front",         "BrakePresF", HT_BRAKE_PRESSURE_FRONT,   0x36B,  0,       1,     UNIT_KPA,       1.0f,   -101.3f, 20,   false,  0,    0.0f,   0},
    {"NOS Press Sensor 1",           "NOSPress1",  HT_NOS_PRESSURE_1,         0x36B,  2,       3,     UNIT_KPA,       0.22f,  -101.3f, 20,   false,  0,    0.0f,   0},
    {"Turbo Speed Sensor 1",         "TurboSpd1",  HT_TURBO_SPEED_1,          0x36B,  4,       5,     UNIT_RPM,       10.0f,  0.0f,    20,   false,  0,    0.0f,   0},
    {"Lateral G",                    "LatG",       HT_LATERAL_G,              0x36B,  6,       7,     UNIT_MPS2,      0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Whl Speed Front Left",         "WhlSpdFL",   HT_WHEEL_SPEED_FL,         0x36C,  0,       1,     UNIT_KPH,       0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Whl Speed Front Right",        "WhlSpdFR",   HT_WHEEL_SPEED_FR,         0x36C,  2,       3,     UNIT_KPH,       0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Whl Speed Rear Left",          "WhlSpdRL",   HT_WHEEL_SPEED_RL,         0x36C,  4,       5,     UNIT_KPH,       0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Whl Speed Rear Right",         "WhlSpdRR",   HT_WHEEL_SPEED_RR,         0x36C,  6,       7,     UNIT_KPH,       0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Exhaust Cam Angle 1",          "ExhCamAng1", HT_EXHAUST_CAM_ANGLE_1,    0x36D,  4,       5,     UNIT_DEGREES,   0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Exhaust Cam Angle 2",          "ExhCamAng2", HT_EXHAUST_CAM_ANGLE_2,    0x36D,  6,       7,     UNIT_DEGREES,   0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Engine Limiting Active",       "LimActive",  HT_ENGINE_LIM_ACTIVE,      0x36E,  0,       1,     UNIT_BOOLEAN,   1.0f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Launch Control Ign Retard",    "LCIgRetard", HT_LC_IGN_RETARD,          0x36E,  2,       3,     UNIT_DEGREES,   0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Launch Control Fuel Enrich",   "LCFuelEnr",  HT_LC_FUEL_ENRICH,         0x36E,  4,       5,     UNIT_PERCENT,   0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Longitudinal G",               "LongG",      HT_LONGITUDINAL_G,         0x36E,  6,       7,     UNIT_MPS2,      0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Generic Output 1 Duty Cycle",  "GenOut1DC",  HT_GENERIC_OUTPUT_1_DUTY,  0x36F,  0,       1,     UNIT_PERCENT,   0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Boost Control Output",         "BoostCtl",   HT_BOOST_CONTROL_OUTPUT,   0x36F,  2,       3,     UNIT_PERCENT,   0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Vehicle Speed",                "VehSpeed",   HT_VEHICLE_SPEED,          0x370,  0,       1,     UNIT_KPH,       0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Intake Cam Angle 1",           "IntCamAng1", HT_INTAKE_CAM_ANGLE_1,     0x370,  4,       5,     UNIT_DEGREES,   0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Intake Cam Angle 2",           "IntCamAng2", HT_INTAKE_CAM_ANGLE_2,     0x370,  6,       7,     UNIT_DEGREES,   0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Fuel Flow",                    "FuelFlow",   HT_FUEL_FLOW,              0x371,  0,       1,     UNIT_CCPM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Fuel Flow Return",             "FuelFloRet", HT_FUEL_FLOW_RETURN,       0x371,  2,       3,     UNIT_CCPM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Battery Voltage",              "BattVolt",   HT_BATTERY_VOLTAGE,        0x372,  0,       1,     UNIT_VOLTS,     0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Target Boost Level",           "BoostTar",   HT_TARGET_BOOST_LEVEL,     0x372,  4,       5,     UNIT_KPA,       0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Barometric Pressure",          "BaroPres",   HT_BARO_PRESSURE,          0x372,  6,       7,     UNIT_KPA_ABS,   0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"EGT Sensor 1",                 "EGT1",       HT_EGT_SENSOR_1,           0x373,  0,       1,     UNIT_DEGREES,   0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"EGT Sensor 2",                 "EGT2",       HT_EGT_SENSOR_2,           0x373,  2,       3,     UNIT_DEGREES,   0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Ambient Air Temperature",      "AmbTemp",    HT_AMBIENT_AIR_TEMP,       0x376,  0,       1,     UNIT_K,         0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Relative Humidity",            "RelHumid",   HT_RELATIVE_HUMIDITY,      0x376,  2,       3,     UNIT_PERCENT,   0.1f,   0.0f,    10,   true,   0,    0.0f,   0},
    {"Specific Humidity",            "SpeHumid",   HT_SPECIFIC_HUMIDITY,      0x376,  4,       5,     UNIT_PPM,       100.0f, 0.0f,    10,   false,  0,    0.0f,   0},
    {"Absolute Humidity",            "AbsHumid",   HT_ABSOLUTE_HUMIDITY,      0x376,  6,       7,     UNIT_GPM3,      0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Coolant Temperature",          "CoolantTmp", HT_COOLANT_TEMPERATURE,    0x3E0,  0,       1,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Air Temperature",              "AirTemp",    HT_AIR_TEMPERATURE,        0x3E0,  2,       3,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Fuel Temperature",             "FuelTemp",   HT_FUEL_TEMPERATURE,       0x3E0,  4,       5,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Oil Temperature",              "OilTemp",    HT_OIL_TEMPERATURE,        0x3E0,  6,       7,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Gearbox Oil Temperature",      "GearOilTmp", HT_GEARBOX_OIL_TEMP,       0x3E1,  0,       1,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Diff Oil Temperature",         "DiffOilTmp", HT_DIFF_OIL_TEMPERATURE,   0x3E1,  2,       3,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Fuel Composition",             "FuelComp",   HT_FUEL_COMPOSITION,       0x3E1,  4,       5,     UNIT_PERCENT,   0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Fuel Level",                   "FuelLevel",  HT_FUEL_LEVEL,             0x3E2,  0,       1,     UNIT_LITERS,    0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Fuel Trim Short Term Bank 1",  "FuelTrmST1", HT_FUEL_TRIM_SHORT_TERM_1, 0x3E3,  0,       1,     UNIT_PERCENT,   0.1f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Fuel Trim Short Term Bank 2",  "FuelTrmST2", HT_FUEL_TRIM_SHORT_TERM_2, 0x3E3,  2,       3,     UNIT_PERCENT,   0.1f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Fuel Trim Long Term Bank 1",   "FuelTrmLT1", HT_FUEL_TRIM_LONG_TERM_1,  0x3E3,  4,       5,     UNIT_PERCENT,   0.1f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Fuel Trim Long Term Bank 2",   "FuelTrmLT2", HT_FUEL_TRIM_LONG_TERM_2,  0x3E3,  6,       7,     UNIT_PERCENT,   0.1f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Neutral Switch",               "NeutralSw",  HT_NEUTRAL_SWITCH,         0x3E4,  1,       1,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   7},
    {"Reverse Switch",               "ReverseSw",  HT_REVERSE_SWITCH,         0x3E4,  1,       1,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   6},
    {"Gear Switch",                  "GearSwitch", HT_GEAR_SWITCH,            0x3E4,  1,       1,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   5},
    {"Decel Cut Active",             "DecelCutAc", HT_DECEL_CUT_ACTIVE,       0x3E4,  1,       1,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   4},
    {"Transient Throttle Active",    "TranThroAc", HT_TRANS_THROTTLE_ACTIVE,  0x3E4,  1,       1,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   3},
    {"Brake Pedal Switch",           "BrakePedal", HT_BRAKE_PEDAL_SWITCH,     0x3E4,  1,       1,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   2},
    {"Clutch Switch",                "ClutchSw",   HT_CLUTCH_SWITCH,          0x3E4,  1,       1,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   1},
    {"Oil Pressure Light",           "OilPresLig", HT_OIL_PRESSURE_LIGHT,     0x3E4,  1,       1,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Launch Control Active",        "LCActive",   HT_LAUNCH_CONTROL_ACTIVE,  0x3E4,  2,       2,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   7},
    {"Launch Control Switch",        "LCSwitch",   HT_LAUNCH_CONTROL_SWITCH,  0x3E4,  2,       2,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   6},
    {"Aux RPM Limiter Active",       "AuxRPMLim",  HT_AUX_RPM_LIMITER_ACTIVE, 0x3E4,  2,       2,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   5},
    {"Flat Shift Switch",            "FlatShifSw", HT_FLAT_SHIFT_SWITCH,      0x3E4,  2,       2,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   3},
    {"Torque Reduction Active",      "TorqRedAct", HT_TORQUE_REDUCT_ACTIVE,   0x3E4,  2,       2,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   1},
    {"Traction Control Enabled",     "TCEnabled",  HT_TC_ENABLED,             0x3E4,  3,       3,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   7},
    {"Traction Control Active",      "TCActive",   HT_TC_ACTIVE,              0x3E4,  3,       3,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   6},
    {"Air Conditioning Request",     "ACRequest",  HT_AIR_CON_REQUEST,        0x3E4,  3,       3,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   5},
    {"Air Conditioning Output",      "ACOutput",   HT_AIR_CON_OUTPUT,         0x3E4,  3,       3,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   4},
    {"Thermo Fan 4 On",              "ThermFan4",  HT_THERMO_FAN_4_ON,        0x3E4,  3,       3,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   3},
    {"Thermo Fan 3 On",              "ThermFan3",  HT_THERMO_FAN_3_ON,        0x3E4,  3,       3,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   2},
    {"Thermo Fan 2 On",              "ThermFan2",  HT_THERMO_FAN_2_ON,        0x3E4,  3,       3,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   1},
    {"Thermo Fan 1 On",              "ThermFan1",  HT_THERMO_FAN_1_ON,        0x3E4,  3,       3,     UNIT_BIT_FIELD, 1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Rotary Trim Pot 1",            "RotTrim1",   HT_ROTARY_TRIM_POT_1,      0x3E4,  4,       4,     UNIT_RAW,       1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Rotary Trim Pot 2",            "RotTrim2",   HT_ROTARY_TRIM_POT_2,      0x3E4,  5,       5,     UNIT_RAW,       1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Rotary Trim Pot 3",            "RotTrim3",   HT_ROTARY_TRIM_POT_3,      0x3E4,  6,       6,     UNIT_RAW,       1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Check Engine Light",           "CEL",        HT_CHECK_ENGINE_LIGHT,     0x3E4,  7,       7,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   7},
    {"Battery Light Active",         "BatLigAct",  HT_BATTERY_LIGHT_ACTIVE,   0x3E4,  7,       7,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   6},
    {"Battery Light State",          "BatLigSt",   HT_HAND_BRAKE_STATE,       0x3E4,  7,       7,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   1},
    {"Traction Control Light",       "TCLight",    HT_TRACTION_CONTROL_LIGHT, 0x3E4,  7,       7,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Ignition Switch",              "IgnSwitch",  HT_IGNITION_SWITCH,        0x3E5,  0,       0,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Turbo Timer Time Remaining",   "TurbTimRem", HT_TURBO_TIMER_TIME_REM,   0x3E5,  1,       1,     UNIT_SECONDS,   1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Turbo Timer Engine Time Rem",  "TurTEngRem", HT_TURB_TIMER_ENG_TIM_REM, 0x3E5,  2,       2,     UNIT_SECONDS,   1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Pit Speed Limit Error",        "PSLError",   HT_PIT_SPEED_LIM_ERROR,    0x3E5,  3,       3,     UNIT_ENUM,      1.0f,   0.0f,    5,    false,  0,    0.0f,   7},
    {"Pit Speed Limit Active",       "PSLActive",  HT_PIT_SPEED_LIM_ACTIVE,   0x3E5,  3,       3,     UNIT_ENUM,      1.0f,   0.0f,    5,    false,  0,    0.0f,   6},
    {"Pit Speed Limit Switch State", "PSLSwitch",  HT_PIT_SPEED_LIM_SW_STATE, 0x3E5,  3,       3,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   5},
    {"ABS Error",                    "ABSError",   HT_ABS_ERROR,              0x3E5,  3,       3,     UNIT_ENUM,      1.0f,   0.0f,    5,    false,  0,    0.0f,   4},
    {"ABS Active",                   "ABSActive",  HT_ABS_ACTIVE,             0x3E5,  3,       3,     UNIT_ENUM,      1.0f,   0.0f,    5,    false,  0,    0.0f,   2},
    {"ABS Armed",                    "ABSArmed",   HT_ABS_ARMED,              0x3E5,  3,       3,     UNIT_ENUM,      1.0f,   0.0f,    5,    false,  0,    0.0f,   1},
    {"Steering Wheel Angle",         "SteerWhAng", HT_STEERING_WHEEL_ANGLE,   0x3E5,  4,       5,     UNIT_DEGREES,   1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Driveshaft RPM",               "DrvshftRPM", HT_DRIVESHAFT_RPM,         0x3E5,  6,       7,     UNIT_RPM,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"NOS Pressure Sensor 2",        "NOSPress2",  HT_NOS_PRESSURE_SENSOR_2,  0x3E6,  0,       1,     UNIT_KPA,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"NOS Pressure Sensor 3",        "NOSPress3",  HT_NOS_PRESSURE_SENSOR_3,  0x3E6,  2,       3,     UNIT_KPA,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"NOS Pressure Sensor 4",        "NOSPress4",  HT_NOS_PRESSURE_SENSOR_4,  0x3E6,  4,       5,     UNIT_KPA,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Turbo Speed Sensor 2",         "TurboSpd2",  HT_TURBO_SPEED_SENSOR_2,   0x3E6,  6,       7,     UNIT_RPM,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 1",             "GenSensor1", HT_GENERIC_SENSOR_1,       0x3E7,  0,       1,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 2",             "GenSensor2", HT_GENERIC_SENSOR_2,       0x3E7,  2,       3,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 3",             "GenSensor3", HT_GENERIC_SENSOR_3,       0x3E7,  4,       5,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 4",             "GenSensor4", HT_GENERIC_SENSOR_4,       0x3E7,  6,       7,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 5",             "GenSensor5", HT_GENERIC_SENSOR_5,       0x3E8,  0,       1,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 6",             "GenSensor6", HT_GENERIC_SENSOR_6,       0x3E8,  2,       3,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 7",             "GenSensor7", HT_GENERIC_SENSOR_7,       0x3E8,  4,       5,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 8",             "GenSensor8", HT_GENERIC_SENSOR_8,       0x3E8,  6,       7,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 9",             "GenSensor9", HT_GENERIC_SENSOR_9,       0x3E9,  0,       1,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Generic Sensor 10",            "GenSenso10", HT_GENERIC_SENSOR_10,      0x3E9,  2,       3,     UNIT_RAW,       1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Target Lambda",                "TarLambda",  HT_TARGET_LAMBDA,          0x3E9,  4,       5,     UNIT_LAMBDA,    1.0f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Nitrous Stage 1 Output State", "NOSS1OutSt", HT_NITROUS_ST_1_OUT_STATE, 0x3E9,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   7},
    {"Nitrous Stage 2 Output State", "NOSS2OutSt", HT_NITROUS_ST_2_OUT_STATE, 0x3E9,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   6},
    {"Nitrous Stage 3 Output State", "NOSS3OutSt", HT_NITROUS_ST_3_OUT_STATE, 0x3E9,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   5},
    {"Nitrous Stage 4 Output State", "NOSS4OutSt", HT_NITROUS_ST_4_OUT_STATE, 0x3E9,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   4},
    {"Nitrous Stage 5 Output State", "NOSS5OutSt", HT_NITROUS_ST_5_OUT_STATE, 0x3E9,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   3},
    {"Nitrous Stage 6 Output State", "NOSS6OutSt", HT_NITROUS_ST_6_OUT_STATE, 0x3E9,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   2},
    {"Water Inj Adv Out State",      "WatInjOtSt", HT_WATER_INJ_AD_OUT_STATE, 0x3E9,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    5,    false,  0,    0.0f,   1},
    {"TM Knob",                      "TqMgmtKnob", HT_TORQUE_MGMT_KNOB,       0x3E9,  7,       7,     UNIT_RAW,       1.0f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Gearbox Line Pressure",        "GearLinePr", HT_GEARBOX_LINE_PRESSURE,  0x3EA,  0,       1,     UNIT_KPA,       0.1f,   -101.3f, 50,   false,  0,    0.0f,   0},
    {"Injection Stage 3 Duty Cycle", "InjS3Duty",  HT_INJ_STAGE_3_DUTY,       0x3EA,  2,       3,     UNIT_PERCENT,   0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Injection Stage 4 Duty Cycle", "InjS4Duty",  HT_INJ_STAGE_4_DUTY,       0x3EA,  4,       5,     UNIT_PERCENT,   0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Crank Case Pressure",          "CrankPres",  HT_CRANK_CASE_PRESSURE,    0x3EA,  6,       7,     UNIT_KPA,       0.1f,   -101.3f, 50,   false,  0,    0.0f,   0},
    {"Race Timer",                   "RaceTimer",  HT_RACE_TIMER,             0x3EB,  0,       3,     UNIT_MS,        1.0f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Ignition Angle Bank 1",        "IgnAngleB1", HT_IGNITION_ANGLE_BANK_1,  0x3EB,  4,       5,     UNIT_DEGREES,   0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"Ignition Angle Bank 2",        "IgnAngleB2", HT_IGNITION_ANGLE_BANK_2,  0x3EB,  6,       7,     UNIT_DEGREES,   0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"TM Drive RPM Target",          "TMRPMTar",   HT_TM_RPM_TARGET,          0x3EC,  0,       1,     UNIT_RPM,       1.0f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"TM Drive RPM Target Error",    "TMRPMError", HT_TM_RPM_ERROR,           0x3EC,  2,       3,     UNIT_RPM,       1.0f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"TM Drive RPM Tar Err Ign Cor", "TMRPMEICor", HT_TM_RPM_ERROR_IGN_CORR,  0x3EC,  4,       5,     UNIT_DEGREES,   0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"TM Drive RPM Timed Ign Cor",   "TMRPMTICor", HT_TM_RPM_TIMED_IGN_CORR,  0x3EC,  6,       7,     UNIT_DEGREES,   0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"TM Combined Ign Correction",   "TMCombICor", HT_TM_COMBINED_IGN_CORR,   0x3ED,  0,       1,     UNIT_DEGREES,   0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"Wideband Sensor 5",            "Wideband5",  HT_WIDEBAND_SENSOR_5,      0x3EE,  0,       1,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 6",            "Wideband6",  HT_WIDEBAND_SENSOR_6,      0x3EE,  2,       3,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 7",            "Wideband7",  HT_WIDEBAND_SENSOR_7,      0x3EE,  4,       5,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 8",            "Wideband8",  HT_WIDEBAND_SENSOR_8,      0x3EE,  6,       7,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 9",            "Wideband9",  HT_WIDEBAND_SENSOR_9,      0x3EF,  0,       1,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 10",           "Wideband10", HT_WIDEBAND_SENSOR_10,     0x3EF,  2,       3,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 11",           "Wideband11", HT_WIDEBAND_SENSOR_11,     0x3EF,  4,       5,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Sensor 12",           "Wideband12", HT_WIDEBAND_SENSOR_12,     0x3EF,  6,       7,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Shock Travel FL Uncalibrated", "STraFLUcal", HT_SHOCK_TRAVEL_FL_UNCAL,  0x3F0,  0,       1,     UNIT_MM,        0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Shock Travel FR Uncalibrated", "STraFRUcal", HT_SHOCK_TRAVEL_FR_UNCAL,  0x3F0,  2,       3,     UNIT_MM,        0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Shock Travel RL Uncalibrated", "STraRLUcal", HT_SHOCK_TRAVEL_RL_UNCAL,  0x3F0,  4,       5,     UNIT_MM,        0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Shock Travel RR Uncalibrated", "STraRRUcal", HT_SHOCK_TRAVEL_RR_UNCAL,  0x3F0,  6,       7,     UNIT_MM,        0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Shock Travel Front Left",      "ShockTraFL", HT_SHOCK_TRAVEL_FL,        0x3F1,  0,       1,     UNIT_MM,        0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"Shock Travel Front Right",     "ShockTraFR", HT_SHOCK_TRAVEL_FR,        0x3F1,  2,       3,     UNIT_MM,        0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"Shock Travel Rear Left",       "ShockTraRL", HT_SHOCK_TRAVEL_RL,        0x3F1,  4,       5,     UNIT_MM,        0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"Shock Travel Rear Right",      "ShockTraRR", HT_SHOCK_TRAVEL_RR,        0x3F1,  6,       7,     UNIT_MM,        0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"ECU Temperature",              "ECUTemp",    HT_ECU_TEMPERATURE,        0x469,  0,       1,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Wideband Overall",             "WO2",        HT_WIDEBAND_OVERALL,       0x470,  0,       1,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Bank 1",              "WidebandB1", HT_WIDEBAND_BANK_1,        0x470,  2,       3,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Wideband Bank 2",              "WidebandB2", HT_WIDEBAND_BANK_2,        0x470,  4,       5,     UNIT_LAMBDA,    0.001f, 0.0f,    20,   false,  0,    0.0f,   0},
    {"Gear Selector Position",       "GearSelPos", HT_GEAR_SELECTOR_POS,      0x470,  6,       6,     UNIT_ENUM,      1.0f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Gear",                         "Gear",       HT_GEAR,                   0x470,  7,       7,     UNIT_ENUM,      1.0f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Injector Pressure Diff",       "InjPresDif", HT_PRESSURE_DIFFERENTIAL,  0x471,  0,       1,     UNIT_KPA,       0.1f,   0.0f,    50,   true,   0,    0.0f,   0},
    {"Accelerator Pedal Position",   "AccPedPos",  HT_ACCELERATOR_PEDAL_POS,  0x471,  2,       3,     UNIT_PERCENT,   0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Exhaust Manifold Pressure",    "ExhManPres", HT_EXHAUST_MANIFOLD_PRESS, 0x471,  4,       5,     UNIT_KPA,       0.1f,   0.0f,    50,   false,  0,    0.0f,   0},
    {"Cruise Control Target Speed",  "CCTarget",   HT_CC_TARGET_SPEED,        0x472,  0,       1,     UNIT_KPH,       0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Cruise Control Last Target",   "CCLastTar",  HT_CC_LAST_TARGET_SPEED,   0x472,  2,       3,     UNIT_KPH,       0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Cruise Control Speed Error",   "CCError",    HT_CC_SPEED_ERROR,         0x472,  4,       5,     UNIT_KPH,       0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Cruise Control State",         "CCState",    HT_CC_STATE,               0x472,  6,       6,     UNIT_ENUM,      1.0f,   0.0f,    20,   false,  0,    0.0f,   0}, // 6:7..6:4
    {"Cruise Control Input State",   "CCInState",  HT_CC_INPUT_STATE,         0x472,  6,       7,     UNIT_BIT_FIELD, 1.0f,   0.0f,    20,   false,  0,    0.0f,   0}, // 6:3..7:0
    {"Total Fuel Used",              "TotFuelUse", HT_TOTAL_FUEL_USED,        0x473,  0,       3,     UNIT_CC,        1.0f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Rolling Antilag Switch State", "RollALSt",   HT_ROLLING_AL_SW_STATE,    0x473,  4,       4,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   7},
    {"Antilag Switch State",         "ALSwSt",     HT_AL_SWITCH_STATE,        0x473,  4,       4,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   6},
    {"Antilag Output State",         "ALOutSt",    HT_AL_OUTPUT_STATE,        0x473,  4,       4,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   5},
    {"TC Switch State",              "TCSwitchSt", HT_TC_SWITCH_STATE,        0x473,  4,       4,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   4},
    {"Primary Fuel Pump Out State",  "PriFPOutSt", HT_PRI_FP_OUTPUT_STATE,    0x473,  4,       4,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   3},
    {"Aux 1 Fuel Pump Output State", "Ax1FPOutSt", HT_AUX1_FP_OUTPUT_STATE,   0x473,  4,       4,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   2},
    {"Aux 2 Fuel Pump Output State", "Ax2FPOutSt", HT_AUX2_FP_OUTPUT_STATE,   0x473,  4,       4,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   1},
    {"Aux 3 Fuel Pump Output State", "Ax3FPOutSt", HT_AUX3_FP_OUTPUT_STATE,   0x473,  4,       4,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Nitrous En 1 Switch State",    "N2OEn1SwSt", HT_N2O_ENABLE1_SW_STATE,   0x473,  5,       5,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   7},
    {"Nitrous En 1 Output State",    "N2OEn1OtSt", HT_N2O_ENABLE1_OUT_STATE,  0x473,  5,       5,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   6},
    {"Nitrous En 2 Switch State",    "N2OEn2SwSt", HT_N2O_ENABLE2_SW_STATE,   0x473,  5,       5,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   5},
    {"Nitrous En 2 Output State",    "N2OEn2OtSt", HT_N2O_ENABLE2_OUT_STATE,  0x473,  5,       5,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   4},
    {"Nitrous En 3 Switch State",    "N2OEn3SwSt", HT_N2O_ENABLE3_SW_STATE,   0x473,  5,       5,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   3},
    {"Nitrous En 3 Output State",    "N2OEn3OtSt", HT_N2O_ENABLE3_OUT_STATE,  0x473,  5,       5,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   2},
    {"Nitrous En 4 Switch State",    "N2OEn4SwSt", HT_N2O_ENABLE4_SW_STATE,   0x473,  5,       5,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   1},
    {"Nitrous En 4 Output State",    "N2OEn4OtSt", HT_N2O_ENABLE4_OUT_STATE,  0x473,  5,       5,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Nitrous Override 1 Switch St", "N2OOv1SwSt", HT_N2O_OVR1_SW_STATE,      0x473,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   7},
    {"Nitrous Override 1 Output St", "N2OOv1OtSt", HT_N2O_OVR1_OUT_STATE,     0x473,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   6},
    {"Nitrous Override 2 Switch St", "N2OOv2SwSt", HT_N2O_OVR2_SW_STATE,      0x473,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   5},
    {"Nitrous Override 2 Output St", "N2OOv2OtSt", HT_N2O_OVR2_OUT_STATE,     0x473,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   4},
    {"Nitrous Override 3 Switch St", "N2OOv3SwSt", HT_N2O_OVR3_SW_STATE,      0x473,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   3},
    {"Nitrous Override 3 Output St", "N2OOv3OtSt", HT_N2O_OVR3_OUT_STATE,     0x473,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   2},
    {"Nitrous Override 4 Switch St", "N2OOv4SwSt", HT_N2O_OVR4_SW_STATE,      0x473,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   1},
    {"Nitrous Override 4 Output St", "N2OOv4OtSt", HT_N2O_OVR4_OUT_STATE,     0x473,  6,       6,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Water Inj Adv En Switch St",   "WIAEnSwSt",  HT_WATER_INJ_EN_SWITCH,    0x473,  7,       7,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   7},
    {"Water Inj Adv En Output St",   "WIAEnOutSt", HT_WATER_INJ_EN_OUTPUT,    0x473,  7,       7,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   6},
    {"Water Inj Adv Ovr Switch St",  "WIAOvrSwSt", HT_WATER_INJ_OVR_SWITCH,   0x473,  7,       7,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   5},
    {"Water Inj Adv Ovr Output St",  "WIAOvrOtSt", HT_WATER_INJ_OVR_OUTPUT,   0x473,  7,       7,     UNIT_BOOLEAN,   1.0f,   0.0f,    10,   false,  0,    0.0f,   4},
    {"Cut Percentage Method",        "CutPerMeth", HT_CUT_PERCENTAGE_METHOD,  0x473,  7,       7,     UNIT_ENUM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0}, // 7:3..7:0
    {"Vertical G",                   "VerticalG",  HT_VERTICAL_G,             0x474,  0,       1,     UNIT_MPS2,      0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Pitch Rate",                   "PitchRate",  HT_PITCH_RATE,             0x474,  2,       3,     UNIT_DEG_S,     0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Roll Rate",                    "RollRate",   HT_ROLL_RATE,              0x474,  4,       5,     UNIT_DEG_S,     0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Yaw Rate",                     "YawRate",    HT_YAW_RATE,               0x474,  6,       7,     UNIT_DEG_S,     0.1f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Primary Fuel Pump Duty Cycle", "PriFPDC",    HT_PRIMARY_FUEL_PUMP_DUTY, 0x475,  0,       1,     UNIT_PERCENT,   0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Aux 1 Fuel Pump Duty Cycle",   "Aux1FPDC",   HT_AUX1_FUEL_PUMP_DUTY,    0x475,  2,       3,     UNIT_PERCENT,   0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Aux 2 Fuel Pump Duty Cycle",   "Aux2FPDC",   HT_AUX2_FUEL_PUMP_DUTY,    0x475,  4,       5,     UNIT_PERCENT,   0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Aux 3 Fuel Pump Duty Cycle",   "Aux3FPDC",   HT_AUX3_FUEL_PUMP_DUTY,    0x475,  6,       7,     UNIT_PERCENT,   0.1f,   0.0f,    5,    false,  0,    0.0f,   0},
    {"Brake Pressure Rear",          "BrPresRear", HT_BRAKE_PRESSURE_REAR,    0x476,  0,       1,     UNIT_KPA,       1.0f,   -101.3f, 20,   false,  0,    0.0f,   0},
    {"Brake Pressure Front Ratio",   "BrPresFRat", HT_BRAKE_PRESSURE_F_RATIO, 0x476,  2,       3,     UNIT_PERCENT,   0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Brake Pressure Rear Ratio",    "BrPresRRat", HT_BRAKE_PRESSURE_R_RATIO, 0x476,  4,       5,     UNIT_PERCENT,   0.1f,   0.0f,    20,   false,  0,    0.0f,   0},
    {"Brake Pressure Difference",    "BrPresDiff", HT_BRAKE_PRESSURE_DIFF,    0x476,  6,       7,     UNIT_KPA,       1.0f,   0.0f,    20,   true,   0,    0.0f,   0},
    {"Eng Limit Max",                "EngLimMax",  HT_ENGINE_LIMIT_MAX,       0x477,  0,       1,     UNIT_RPM,       1.0f,   0.0f,    10,   false,  0,    0.0f,   0}, 
    {"Cut Percent",                  "CutPercent", HT_CUT_PERCENTAGE,         0x477,  1,       2,     UNIT_PERCENT,   0.1f,   0.0f,    10,   false,  0,    0.0f,   0}, 
    {"Eng Limit Function",           "EngLimFunc", HT_ENGINE_LIMIT_FUNCTION,  0x477,  4,       4,     UNIT_ENUM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0}, 
    {"RPM Lim Function",             "RPMLimFunc", HT_RPM_LIMIT_FUNCTION,     0x477,  5,       5,     UNIT_ENUM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0}, 
    {"Cut Percent Function",         "CutPerFunc", HT_CUT_PERCENTAGE_FUNC,    0x477,  6,       6,     UNIT_ENUM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0}, 
    {"Eng Limit Method",             "EngLimMeth", HT_ENGINE_LIMIT_METHOD,    0x477,  7,       7,     UNIT_ENUM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0}, 
    {"RPM Limit Method",             "RPMLimMeth", HT_RPM_LIMIT_METHOD,       0x477,  7,       7,     UNIT_ENUM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0}, 
    {"Tire Pressure FL",             "TirePresFL", HT_TIRE_PRESSURE_FL,       0x6F0,  0,       1,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0}, 
    {"Tire Pressure FR",             "TirePresFR", HT_TIRE_PRESSURE_FR,       0x6F0,  2,       3,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0}, 
    {"Tire Pressure RL",             "TirePresRL", HT_TIRE_PRESSURE_RL,       0x6F0,  4,       5,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0}, 
    {"Tire Pressure RR",             "TirePresRR", HT_TIRE_PRESSURE_RR,       0x6F0,  6,       7,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0}, 
    {"Tire Temperature FL",          "TireTempFL", HT_TIRE_TEMPERATURE_FL,    0x6F1,  0,       1,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0}, 
    {"Tire Temperature FR",          "TireTempFR", HT_TIRE_TEMPERATURE_FR,    0x6F1,  2,       3,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0}, 
    {"Tire Temperature RL",          "TireTempRL", HT_TIRE_TEMPERATURE_RL,    0x6F1,  4,       5,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0}, 
    {"Tire Temperature RR",          "TireTempRR", HT_TIRE_TEMPERATURE_RR,    0x6F1,  6,       7,     UNIT_K,         0.1f,   0.0f,    5,    false,  0,    0.0f,   0}, 
    {"Tire Sensor Battery Volt FL",  "TireBatVFL", HT_TIRE_SENSOR_BATTERY_FL, 0x6F2,  0,       1,     UNIT_VOLTS,     0.001f, 0.0f,    5,    false,  0,    0.0f,   0}, 
    {"Tire Sensor Battery Volt FR",  "TireBatVFR", HT_TIRE_SENSOR_BATTERY_FR, 0x6F2,  2,       3,     UNIT_VOLTS,     0.001f, 0.0f,    5,    false,  0,    0.0f,   0}, 
    {"Tire Sensor Battery Volt RL",  "TireBatVRL", HT_TIRE_SENSOR_BATTERY_RL, 0x6F2,  4,       5,     UNIT_VOLTS,     0.001f, 0.0f,    5,    false,  0,    0.0f,   0}, 
    {"Tire Sensor Battery Volt RR",  "TireBatVRR", HT_TIRE_SENSOR_BATTERY_RR, 0x6F2,  6,       7,     UNIT_VOLTS,     0.001f, 0.0f,    5,    false,  0,    0.0f,   0}, 
    {"Recommended Tire Pres Front",  "RecTirePrF", HT_REC_TIRE_PRESSURE_F,    0x6F3,  0,       1,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0},
    {"Recommended Tire Pres Rear",   "RecTirePrR", HT_REC_TIRE_PRESSURE_R,    0x6F3,  2,       3,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0},
    {"Tire Leak Detected R Right",   "TireLeakRR", HT_TIRE_LEAK_RR,           0x6F3,  4,       4,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   3},
    {"Tire Leak Detected R Left",    "TireLeakRL", HT_TIRE_LEAK_RL,           0x6F3,  4,       4,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   2},
    {"Tire Leak Detected F Right",   "TireLeakFR", HT_TIRE_LEAK_FR,           0x6F3,  4,       4,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   1},
    {"Tire Leak Detected F Left",    "TireLeakFL", HT_TIRE_LEAK_FL,           0x6F3,  4,       4,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0},
    {"Engine Protection Sev Level",  "EPSevLevel", HT_ENGINE_PROTECTION_SEV,  0x6F3,  5,       5,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0},
    {"Engine Protection Reason",     "EPReason",   HT_ENGINE_PROTECTION_REA,  0x6F3,  6,       7,     UNIT_KPA,       0.1f,   -101.3f, 5,    false,  0,    0.0f,   0},
    {"Light State Park",             "LightState", HT_LIGHT_STATE_PARK,       0x6F4,  0,       0,     UNIT_BOOLEAN,   1.0f,   0.0f,    100,  false,  0,    0.0f,   0},
    {"Light State Head",             "LightState", HT_LIGHT_STATE_HEAD,       0x6F4,  0,       0,     UNIT_BOOLEAN,   1.0f,   0.0f,    100,  false,  0,    0.0f,   1},
    {"Light State High Beam",        "LightState", HT_LIGHT_STATE_HIGH,       0x6F4,  0,       0,     UNIT_BOOLEAN,   1.0f,   0.0f,    100,  false,  0,    0.0f,   2},
    {"Light State Left Indicator",   "LightState", HT_LIGHT_STATE_LEFT,       0x6F4,  0,       0,     UNIT_BOOLEAN,   1.0f,   0.0f,    100,  false,  0,    0.0f,   3},
    {"Light State Right Indicator",  "LightState", HT_LIGHT_STATE_RIGHT,      0x6F4,  0,       0,     UNIT_BOOLEAN,   1.0f,   0.0f,    100,  false,  0,    0.0f,   4},
    {"Total Fuel Used T1",           "FUELUSE",    HT_TOTAL_FUEL_USED_T1,     0x6F6,  0,       3,     UNIT_CC,        1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Trip Meter 1",                 "TRIP",       HT_TRIP_METER_1,           0x6F6,  4,       7,     UNIT_METERS,    1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"Generic Output 1-20 States",   "GenOut1-20", HT_GEN_OUT_STATES,         0x6F7,  0,       3,     UNIT_ENUM,      1.0f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Calculated Air Temperature",   "CalAirTemp", HT_CALCULATED_AIR_TEMP,    0x6F7,  4,       5,     UNIT_K,         0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Water Injection Adv Duty",     "WaterADuty", HT_WATER_INJ_ADV_DUTY,     0x6F7,  6,       7,     UNIT_PERCENT,   0.1f,   0.0f,    10,   false,  0,    0.0f,   0},
    {"Exhaust Cutout State",         "EXHCUT",     HT_EXHAUST_CUTOUT_STATE,   0x6F8,  0,       0,     UNIT_ENUM,      -1.0f,  0.0f,    5,    true,   0,    0.0f,   0},
    {"Nitrous Bottle Opener State",  "NSTATE",     HT_N2O_BOTTLE_OPEN_STATE,  0x6F8,  1,       1,     UNIT_ENUM,      1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"",               "",                         HT_GEN_OL_MOTOR_CONT_1_ST, 0x6F8,  2,       2,     UNIT_ENUM,      1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"",               "",                         HT_GEN_OL_MOTOR_CONT_2_ST, 0x6F8,  3,       3,     UNIT_ENUM,      1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"",               "",                         HT_GEN_OL_MOTOR_CONT_3_ST, 0x6F8,  4,       4,     UNIT_ENUM,      1.0f,   0.0f,    5,    true,   0,    0.0f,   0},
    {"",               "",                         HT_RESERVED,               0x700,  0,       1,     UNIT_RAW,       1.0f,   0.0f,    50,   false,  0,    0.0f,   0},
};
