#ifndef _MAIN_H
#define _MAIN_H

typedef enum {
    HT_RPM,
    HT_MANIFOLD_PRESSURE,
    HT_THROTTLE_POSITION,
    HT_COOLANT_PRESSURE,
    HT_FUEL_PRESSURE,
    HT_OIL_PRESSURE,
    HT_ENGINE_DEMAND,
    HT_WASTEGATE_PRESSURE,
    HT_INJECTION_STATE_1_DUTY_CYCLE,
    HT_INJECTION_STATE_2_DUTY_CYCLE,
    HT_IGNITION_ANGLE,
    HT_WHEEL_SLIP,
    HT_WHEEL_DIFF,
    HT_LAUNCH_CONTROL_END_RPM,
    HT_WIDEBAND_SENSOR_1,
    HT_KNOCK_LEVEL_1,
    HT_WHEEL_SPEED_REAR_RIGHT,
    HT_BOOST_CONTROL_OUTPUT,
    HT_VEHICLE_SPEED,
    HT_INTAKE_CAM_ANGLE_1,
    HT_BATTERY_VOLTAGE,
    HT_TARGET_BOOST_LEVEL,
    HT_COOLANT_TEMPERATURE,
    HT_AIR_TEMPERATURE,
    HT_OIL_TEMPERATURE,
    HT_FUEL_TRIM_SHORT_TERM_BANK_1,
    HT_FUEL_TRIM_LONG_TERM_BANK_1,
    HT_IGNITION_ANGLE_BANK_1,
    HT_WIDEBAND_OVERALL,
    HT_GEAR,
    HT_WATER_INJECTION_ADVANCED_SOLENOID_DUTY_CYCLE
} HaltechValue_e;

extern const char* ht_names[];
extern const char* ht_names_short[];

#endif // _MAIN_H