name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install project dependencies
        run: pio pkg install

      - name: Comment out User_Setup.h include
        run: |
          find .pio/libdeps -name "User_Setup_Select.h" -exec sed -i 's/^#include <User_Setup\.h>/#\/\/#include <User_Setup.h>/' {} \;

      - name: Build PlatformIO Project
        run: pio run

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/*/firmware.bin
          retention-days: 30
